# Site settings
url: "https://sudo.ubuntu-tr.net"

theme: ubuntu-tr
themeDir: theme/ubuntu-tr
listDir: theme/ubuntu-tr/_layouts/list
blockDir: theme/ubuntu-tr/_layouts/block
layouts_dir:  ./theme/ubuntu-tr/_layouts
includes_dir: .

disqus_id: sudoportal

# Build settings
markdown: kramdown
highlighter: rouge

timezone: Europe/Istanbul

collections:
  category:
    output: true
    permalink: /:title/
  tag:
    output: true
    permalink: /etiket/:path
  other:
    output: true
    permalink: /o/:title
  root:
    output: true
    permalink: /:path

defaults:
  - scope:
      path: ""
      type: category
    values:
      type: categories
      layout: layout121
  - scope:
      path: ""
      type: tag
    values:
      type: tags
      layout: layout121
  - scope:
      path: ""
      type: posts
    values:
      type: posts
      layout: layout121
  - scope:
      path: ""
      type: other
    values:
      type: others
      layout: layout121
