# Site settings
themeDir: theme/ubuntu-tr
layouts_dir:  ./theme/ubuntu-tr/_layouts
includes_dir: ./theme/ubuntu-tr/_includes

disqus_id: sudoportal

# Build settings
markdown: kramdown
highlighter: rouge

timezone: Europe/Istanbul

collections:
  category:
    output: true
    permalink: /:title/
  tag:
    output: true
    permalink: /etiket/:path
  other:
    output: true
    permalink: /o/:title
  pages:
    output: true
    permalink: /:path
  root:
    output: true
    permalink: /:path

defaults:
  - scope:
      path: ""
      type: category
    values:
      type: categories
      layout: categories
  - scope:
      path: ""
      type: tag
    values:
      type: tags
      layout: tags
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: pages
    values:
      layout: page
  - scope:
      path: ""
      type: other
    values:
      layout: others
