# Site settings
title: Ubuntu-Tr Sudo
#url: "http://localhost:4000/" # the base hostname & protocol for your site
url: "http://ubuntu-tr.github.io/" # the base hostname & protocol for your site

# Build settings
markdown: redcarpet
highlighter: rouge

exclude: ['node_modules', 'Gruntfile.js', 'package.json']
gems: [jekyll-paginate]

# YB Settings
excerpt_separator: <!-- more -->
paginate: 4
comments: false

collections:
  kategori:
    output: true
  etiket:
    output: true

defaults:
  - scope:
      path: ""
      type: kategori
    values:
      type: categories
      layout: kategori_sayfasi
  - scope:
      path: ""
      type: etiket
    values:
      type: tags
      layout: kategori_sayfasi
  - scope:
      path: ""
      type: posts
    values:
      layout: makale_sayfasi