# Site settings
title: Ubuntu-Tr Sudo
#url: "http://localhost:4000" # the base hostname & protocol for your site
url: "https://ubuntu-tr.github.io" # the base hostname & protocol for your site
theme: ubuntu-tr
themeDir: theme/ubuntu-tr

# Where things are
layouts_dir:  ./theme/ubuntu-tr/_layouts
includes_dir: ./theme/ubuntu-tr/_includes

# Build settings
markdown: kramdown
highlighter: rouge

timezone: Europe/Istanbul

exclude: ['node_modules', 'Gruntfile.js', 'package.json']
gems: [jekyll-paginate]

# YB Settings
excerpt_separator: <!-- more -->
paginate: 4
comments: false

collections:
  category:
    output: true
    permalink: /:title/
  tag:
    output: true
    permalink: /etiket/:path
  o:
    output: true
  pages:
    output: true
    permalink: /:path
  root:
    output: true
    permalink: /:path

defaults:
  - scope:
      path: ""
      type: category
    values:
      type: categories
      layout: categories
  - scope:
      path: ""
      type: tag
    values:
      type: tags
      layout: tags
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: pages
    values:
      layout: page
  - scope:
      path: "basic"
      type: pages
    values:
      layout: 
  - scope:
      path: ""
      type: o
    values:
      layout: others
