style: "style1"

index: 
  title: "SUDO Portal"
  description: "Linux ile ilgili haberleri, uygulamaları ve incelemeleri içerir."

posts:
  title: "*title"

categories:
  title: "*title Makaleleri"

tags:
  title: "*title  Makaleleri"

others:
  title: "*title  Makaleleri"

